# Runs after merge to main

trigger:
  - main

variables:
  - group: radius-angular
  - name: projectName
    value: $[variables.PROJECT_NAME]
  - name: feedName
    value: $[variables.FEED_NAME]
  - name: personalAccessToken
    value: $[variables.PERSONAL_ACCESS_TOKEN]
  - name: orgName
    value: $[variables.ORG_NAME]

jobs:
  - job: setup_build_publish
    pool:
      vmImage: ubuntu-latest
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: "14.x"
            displayName: "Install Node.js"
            script: |
              npm ci
              npm run lint
              npm run test
              npm run build:ds
          displayName: "Install lint, test, build DS"
        - task: CopyFiles@2
          displayName: "Copy scripts"
          inputs:
            sourceFolder: "$(Build.SourcesDirectory)/dist/**"
            targetFolder: "$(Build.ArtifactStagingDirectory)/dist"
        - task: PublishBuildArtifacts@1
          displayName: "Publish build artifacts"
          inputs:
            pathToPublish: "$(Build.ArtifactStagingDirectory)/dist"
            artifactName: dist

    # Publish Universal Package
  - job: publish_universal
    steps:
      - task: UniversalPackages@0
        displayName: "Universal package publishing"
        inputs:
          command: publish
          publishDirectory: dist
          vstsFeedPublish: "$(projectName)/$(feedName)"
          vstsFeedPackage: "radius-angular"
          vstsPackageVersion: "0.0.1"
  - job: publish_npm
    steps:
      - bash: echo $(Build.QueuedById) $(orgName)
        env:
          BUILD_QUEUEDBYID: $(Build.QueuedById)
          BUILD_REQUESTEDFOREMAIL: $(Build.RequestedForEmail)
          script:
            $ORG_NAME=$(orgName) $BUILD_QUEUEDBYID=$(Build.QueuedById) $BUILD_REQUESTEDFOREMAIL=$(Build.RequestedForEmail) $PROJECT_NAME=$(projectName) $FEED_NAME=$(feedName) $PERSONAL_ACCESS_TOKEN=$(personalAccessToken) $ORG_NAME=$(System.CollectionId) chmod +x ./npmrc.sh
            vsts-npm-auth -config .npmrc
      - task: Npm@1
        displayName: "Publish to npm"
        inputs:
          command: publish
          publishRegistry: useExternalRegistry
          publishEndpoint: "azureSubscription"
