# Runs after merge to main

trigger:
  - main
  - feature/R20-22-azure-pipelines

variables:
  - group: radius-angular
  - name: projectName
    value: $[variables.PROJECT_NAME]
  - name: feedName
    value: $[variables.FEED_NAME]
  - name: personalAccessToken
    value: $[variables.PERSONAL_ACCESS_TOKEN]
  - name: orgName
    value: $[variables.ORG_NAME]
  - name: GitHubToken
    value: $[variables.GH_TOKEN]
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm

jobs:
  - job: install
    pool:
      vmImage: ubuntu-latest
      steps:
        - checkout: self
          persistCredentials: true

        - task: NodeTool@0
          inputs:
            versionSpec: "14.x"
          displayName: "Install Node"
        - task: Cache@2
          displayName: "Cache npm packages"
          inputs:
            key: 'npm | "$(Agent.OS)" | package-lock.json'
            restoreKeys: |
              npm | "$(Agent.OS)"
            path: $(npm_config_cache)
        - script: npm ci
          displayName: "cache exists; Node clean install"
          condition: ne(variables.CACHE_RESTORED, 'true')
        - script: npm run lint
          displayName: "Lint"
        - script: npm run test
          displayName: "Test"
        - script: npm run build:ds
          displayName: "Build design system package"
        - script: npm pack
          displayName: "Package for npm release"
        - publish: "$(Build.ArtifactStagingDirectory)/dist"
          displayName: "Publish to Artifact Staging Dir"
          artifact: dist
