# This is a package publishing workflow
name: release package

# only works on merge to main or creation of release branch
on:
  push:
    branches:
      - main
      - release

  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
          always-auth: true
          cache-dependency-path: "**/package-lock.json"

      - run: |
          npm ci 
          npm run build

      - name: Test
        id: test
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: build

    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run build:ds && npm pack
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
